# Generated by Django 2.1.7 on 2023-06-28 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230628_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 28, 18, 53, 5, 298597)),
        ),
    ]
